name: Deployment

on:
  workflow_dispatch:

env: 
  HOST: cassini.cs.kent.edu
  USER: jxl318
  PORT: 9358
  TARGET: jxl318@cassini.cs.kent.edu
  APP: webapp
  RUN: ssh -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no jxl318@cassini.cs.kent.edu
  COPY: scp -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

jobs:
  deployment:
    name: Deploy Software
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ID_ED25519 }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Examine Server Environment
        run: | 
          echo $ $RUN hostname
          $RUN hostname 
          echo $ $RUN pwd
          $RUN pwd
          echo $ $RUN ls -la 
          $RUN ls -la

      - name: Deplot the hello page
        run: |
          $ RUN screen -S $USER:$APP -X quit || true
          $COPY index.html $TARGET:.
          $RUN screen -dmS $USER:$APP python -m http.server $PORT